### ISSUE TITLE
/src/cuda.c:38: void check_error(cudaError_t): Assertion `0' failed

### ISSUE THREAD

**Issue by halt9** [prabindh/darknet#27]
In the most recent version, Darknet compiles, arapaho compiles, but when I try to run arapaho.out I get the following error:

```
layer     filters    size              input                output
    0 CUDA Error: unknown error
arapaho.out: ./src/cuda.c:38: void check_error(cudaError_t): Assertion `0' failed.
[1]    25865 abort (core dumped)  LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./arapaho.out

```

As per issue #17 I was previously able to run arapaho, but with this new version, I can't. The Makefile I'm using contains:

```
LDFLAGS= -lm -pthread 
COMMON= 
CFLAGS=-Wall -Wfatal-errors 

OPTS=-O0 -g
CFLAGS+=$(OPTS)

COMMON+= -DGPU -I/usr/local/cuda/include/
CFLAGS+= -DGPU
LDFLAGS+= -L/usr/local/cuda/lib64 -lcuda -lcudart -lcublas -lcurand

COMMON+= -DCUDNN 
CFLAGS+= -DCUDNN
LDFLAGS+= -lcudnn

COMMON+= -DOPENCV
CFLAGS+= -DOPENCV
LDFLAGS+= `pkg-config --libs opencv-3.2.0-dev` 
COMMON+= `pkg-config --cflags opencv-3.2.0-dev` 


arapaho: clean
	g++ test.cpp arapaho.cpp  $(COMMON) $(CFLAGS) -I../src/ -L./ $(LDFLAGS) -ldarknet-cpp-shared -std=c++11 -o arapaho.out

clean:
	rm -rf ./arapaho.out	

```

And I've made sure that all these flags are matched to the makefile for darknet-cpp-shared itself.

**Comment by prabindh** [comment]
Could you try reverting the last patch (https://github.com/prabindh/darknet/commit/cdff53ece784229c3fd122d3b8bd1da94eaeb178) ?

**Comment by halt9** [comment]
Just did that, still getting the same error. For reference, the version I had working was 0e66eed

**Comment by prabindh** [comment]
Is this repeatable ?

**Comment by halt9** [comment]
I only have one machine to test on but I deleted the repo and redownloaded it and built both darknet and arapaho from scratch and I have the same issue. I'll do some more testing and report back.

**Comment by halt9** [comment]
I fixed this issue. It was caused by a previous run of arapaho not terminating properly. A previous user ran it and it somehow got left on the nvidia-smi task manager. I sigkill'd the process thinking that would be good enough, but clearly it wasn't. A hard reboot solved the issue.
